services:

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
  
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cisco
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8989:8080"